; sprite ids
; OverworldSprites indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE ; 00
	const SPRITE_CHRIS ; 01
	const SPRITE_CHRIS_BIKE ; 02
	const SPRITE_GAMEBOY_KID ; 03
	const SPRITE_SILVER ; 04
	const SPRITE_OAK ; 05
	const SPRITE_RED ; 06
	const SPRITE_BLUE ; 07
	const SPRITE_BILL ; 08
	const SPRITE_ELDER ; 09
	const SPRITE_JANINE ; 0a
	const SPRITE_KURT ; 0b
	const SPRITE_MOM ; 0c
	const SPRITE_BLAINE ; 0d
	const SPRITE_REDS_MOM ; 0e
	const SPRITE_DAISY ; 0f
	const SPRITE_ELM ; 10
	const SPRITE_WILL ; 11
	const SPRITE_FALKNER ; 12
	const SPRITE_WHITNEY ; 13
	const SPRITE_BUGSY ; 14
	const SPRITE_MORTY ; 15
	const SPRITE_CHUCK ; 16
	const SPRITE_JASMINE ; 17
	const SPRITE_PRYCE ; 18
	const SPRITE_CLAIR ; 19
	const SPRITE_BROCK ; 1a
	const SPRITE_KAREN ; 1b
	const SPRITE_BRUNO ; 1c
	const SPRITE_MISTY ; 1d
	const SPRITE_LANCE ; 1e
	const SPRITE_SURGE ; 1f
	const SPRITE_ERIKA ; 20
	const SPRITE_KOGA ; 21
	const SPRITE_SABRINA ; 22
	const SPRITE_COOLTRAINER_M ; 23
	const SPRITE_COOLTRAINER_F ; 24
	const SPRITE_BUG_CATCHER ; 25
	const SPRITE_TWIN ; 26
	const SPRITE_YOUNGSTER ; 27
	const SPRITE_LASS ; 28
	const SPRITE_TEACHER ; 29
	const SPRITE_BEAUTY ; 2a
	const SPRITE_SUPER_NERD ; 2b
	const SPRITE_ROCKER ; 2c
	const SPRITE_POKEFAN_M ; 2d
	const SPRITE_POKEFAN_F ; 2e
	const SPRITE_GRAMPS ; 2f
	const SPRITE_GRANNY ; 30
	const SPRITE_SWIMMER_GUY ; 31
	const SPRITE_SWIMMER_GIRL ; 32
	const SPRITE_BIG_SNORLAX ; 33
	const SPRITE_SURFING_PIKACHU ; 34
	const SPRITE_ROCKET ; 35
	const SPRITE_ROCKET_GIRL ; 36
	const SPRITE_NURSE ; 37
	const SPRITE_LINK_RECEPTIONIST ; 38
	const SPRITE_CLERK ; 39
	const SPRITE_FISHER ; 3a
	const SPRITE_FISHING_GURU ; 3b
	const SPRITE_SCIENTIST ; 3c
	const SPRITE_KIMONO_GIRL ; 3d
	const SPRITE_SAGE ; 3e
	const SPRITE_UNUSED_GUY ; 3f
	const SPRITE_GENTLEMAN ; 40
	const SPRITE_BLACK_BELT ; 41
	const SPRITE_RECEPTIONIST ; 42
	const SPRITE_OFFICER ; 43
	const SPRITE_CAL ; 44
	const SPRITE_SLOWPOKE ; 45
	const SPRITE_CAPTAIN ; 46
	const SPRITE_BIG_LAPRAS ; 47
	const SPRITE_GYM_GUIDE ; 48
	const SPRITE_SAILOR ; 49
	const SPRITE_BIKER ; 4a
	const SPRITE_PHARMACIST ; 4b
	const SPRITE_MONSTER ; 4c
	const SPRITE_FAIRY ; 4d
	const SPRITE_BIRD ; 4e
	const SPRITE_DRAGON ; 4f
	const SPRITE_BIG_ONIX ; 50
	const SPRITE_N64 ; 51
	const SPRITE_SUDOWOODO ; 52
	const SPRITE_SURF ; 53
	const SPRITE_POKE_BALL ; 54
	const SPRITE_POKEDEX ; 55
	const SPRITE_PAPER ; 56
	const SPRITE_VIRTUAL_BOY ; 57
	const SPRITE_OLD_LINK_RECEPTIONIST ; 58
	const SPRITE_ROCK ; 59
	const SPRITE_BOULDER ; 5a
	const SPRITE_SNES ; 5b
	const SPRITE_FAMICOM ; 5c
	const SPRITE_FRUIT_TREE ; 5d
	const SPRITE_GOLD_TROPHY ; 5e
	const SPRITE_SILVER_TROPHY ; 5f
	const SPRITE_KRIS ; 60
	const SPRITE_KRIS_BIKE ; 61
	const SPRITE_KURT_OUTSIDE ; 62
	const SPRITE_SUICUNE ; 63
	const SPRITE_ENTEI ; 64
	const SPRITE_RAIKOU ; 65
	const SPRITE_STANDING_YOUNGSTER ; 66
	const SPRITE_MEWTWO_OVERWORLD ; 67
 	const SPRITE_CHRIS_RUN ; 68
 	const SPRITE_KRIS_RUN ; 69
 	const SPRITE_GIOVANNI ; 70
NUM_OVERWORLD_SPRITES EQU const_value - 1

; SpriteMons indexes (see data/sprites/sprite_mons.asm)
SPRITE_POKEMON EQU const_value
	const SPRITE_UMBREON ; 71
	const SPRITE_GEODUDE ; 72
	const SPRITE_MURKROW ; 73
	const SPRITE_SCEPTILE ; 74
	const SPRITE_GRENINJA ; 75
	const SPRITE_INFERNAPE ; 76
	const SPRITE_GENGAR ; 77
	const SPRITE_ZUBAT ; 78
	const SPRITE_MAGIKARP ; 79
	const SPRITE_SQUIRTLE ; 7a
	const SPRITE_BAGON ; 7b
	const SPRITE_BUTTERFREE ; 7c
	const SPRITE_ARCTOZOLT ; 7d
	const SPRITE_BELDUM ; 7e
	const SPRITE_PIKACHU ; 7f
	const SPRITE_CLEFAIRY ; 80
	const SPRITE_CHARMANDER ; 81
	const SPRITE_JYNX ; 82
	const SPRITE_STARMIE ; 83
	const SPRITE_BULBASAUR ; 84
	const SPRITE_MAWILE ; 85
	const SPRITE_PILOSWINE ; 86
	const SPRITE_RATICATE ; 87
	const SPRITE_FROAKIE ; 88
	const SPRITE_LITWICK ; 89
	const SPRITE_TAUROS ; 8a
	const SPRITE_CHANDELURE ; 8b
	const SPRITE_MAGNETON ; 8c
	const SPRITE_TREECKO ; 8d
	const SPRITE_RHYPERIOR ; 8e
	const SPRITE_MOLTRES ; 8f
	const SPRITE_CHIMCHAR ; 90
	const SPRITE_GYARADOS ; 91
	const SPRITE_LUGIA ; 92
	const SPRITE_HO_OH ; 93
	const SPRITE_DRAGONITE ; 94
	const SPRITE_ARCEUS ; 95
	const SPRITE_MEWTWO ; 96
	const SPRITE_VOLCARONA ; 97
	const SPRITE_LUCARIO    ; 98
	const SPRITE_TYRANITAR  ; 99
	const SPRITE_METAGROSS  ; 9a
	const SPRITE_SALAMENCE  ; 9b
	const SPRITE_GARCHOMP   ; 9c
	const SPRITE_ZAPDOS     ; 9d
	const SPRITE_ARTICUNO   ; 9e
	const SPRITE_MEW        ; 9f
	const SPRITE_KYOGRE     ; a0
	const SPRITE_GROUDON    ; a1
	const SPRITE_RAYQUAZA   ; a2
	const SPRITE_DEOXYS     ; a3
	const SPRITE_LATIOS     ; a4
	const SPRITE_DIALGA     ; a5
	const SPRITE_PALKIA     ; a6
	const SPRITE_GIRATINA   ; a7
	const SPRITE_REGIGIGAS  ; a8
	const SPRITE_DARKRAI    ; a9
	const SPRITE_GENESECT   ; aa
	const SPRITE_XERNEAS    ; ab
	const SPRITE_YVELTAL    ; ac
	const SPRITE_ZYGARDE    ; ad
	const SPRITE_BLISSEY    ; ae
	const SPRITE_NOCTOWL    ; af
	const SPRITE_HERACROSS  ; b0
	const SPRITE_MILTANK    ; b1
	const SPRITE_NOWN       ; b2
	const SPRITE_LATIAS     ; b3
	const SPRITE_ALAKAZAM   ; b4
	const SPRITE_MACHAMP    ; b5
	const SPRITE_RAICHU     ; b6
	const SPRITE_SHAYMIN    ; b7
	const SPRITE_ABOMASNOW  ; b8
	const SPRITE_PERSIAN    ; b9
	const SPRITE_HOUNDOOM   ; ba
	const SPRITE_CHARIZARD  ; bb
	const SPRITE_ABRA       ; bc
	const SPRITE_ARCANINE   ; bd
	const SPRITE_POLIWRATH  ; be
	const SPRITE_DITTO      ; bf
	const SPRITE_BELLSPROUT ; c0
	const SPRITE_GIBLE      ; c1
	const SPRITE_MAMOSWINE  ; c2
	const SPRITE_CHANSEY    ; c3
	const SPRITE_TOGEKISS   ; c4
	const SPRITE_MR_MIME    ; c5
	const SPRITE_DRATINI    ; c6
	const SPRITE_SEADRA     ; c7
	const SPRITE_DRAGONAIR  ; c8
	const SPRITE_MILOTIC    ; c9
	const SPRITE_DRACOVISH  ; ca
	const SPRITE_KINGDRA    ; cb
	const SPRITE_VENUSAUR   ; cc
	const SPRITE_ESPEON     ; cd
	const SPRITE_RALTS      ; ce
	const SPRITE_AMPHAROS   ; cf
	const SPRITE_SLOWBRO    ; d0
	const SPRITE_MELMETAL   ; d1
	const SPRITE_STARAPTOR  ; d2
	const SPRITE_SOLOSIS    ; d3
	const SPRITE_GASTLY     ; d4
	const SPRITE_EEVEE      ; d5
	const SPRITE_MUDKIP     ; d6
	const SPRITE_BAXCALIBUR ; d7
	const SPRITE_MELTAN     ; d8
	const SPRITE_REUNICLUS  ; d9
	const SPRITE_BLASTOISE  ; da
	const SPRITE_SCIZOR     ; db
	const SPRITE_HYDREIGON  ; dc
	const SPRITE_CONKELDURR ; dd
	const SPRITE_URSALUNA_B ; de
	const SPRITE_MISMAGIUS  ; df
	const SPRITE_EXCADRILL  ; e0
    const SPRITE_URSALUNA   ; e1
	const SPRITE_GALLADE    ; e2
	const SPRITE_GARDEVOIR  ; e3
	const SPRITE_PINSIR     ; e4
	const SPRITE_SCYTHER    ; e5
	const SPRITE_AEGISLASH  ; e6
	const SPRITE_MEOWTH     ; e7
	const SPRITE_MAGMAR     ; e8
	const SPRITE_DEINO      ; e9
	const SPRITE_ELECTABUZZ ; ea
	const SPRITE_SWAMPERT   ; eb
	const SPRITE_FRIGIBAX   ; ec
	const SPRITE_SMEARGLE   ; ed
NUM_POKEMON_SPRITES EQU const_value - SPRITE_POKEMON

; special GetMonSprite values (see engine/overworld/overworld.asm)
	const_next $ee
	const SPRITE_DAY_CARE_MON_1 ; ee
	const SPRITE_DAY_CARE_MON_2 ; ef

; wVariableSprites indexes (see wram.asm)
	const_next $f0
SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; f0
	const SPRITE_DOLL_1 ; f1
	const SPRITE_DOLL_2 ; f2
	const SPRITE_BIG_DOLL ; f3
	const SPRITE_WEIRD_TREE ; f4
	const SPRITE_OLIVINE_RIVAL ; f5
	const SPRITE_AZALEA_ROCKET ; f6
	const SPRITE_FUCHSIA_GYM_1 ; f7
	const SPRITE_FUCHSIA_GYM_2 ; f8
	const SPRITE_FUCHSIA_GYM_3 ; f9
	const SPRITE_FUCHSIA_GYM_4 ; fa
	const SPRITE_COPYCAT ; fb
	const SPRITE_JANINE_IMPERSONATOR ; fc
